DROP TABLE IF EXISTS customer_TABLESUFFIX;
DROP EXTERNAL WEB TABLE IF EXISTS e_customer_TABLESUFFIX;

CREATE TABLE customer_TABLESUFFIX (
    C_CUSTKEY     INTEGER NOT NULL,
    C_NAME        VARCHAR(25) NOT NULL,
    C_ADDRESS     VARCHAR(40) NOT NULL,
    C_NATIONKEY   INTEGER NOT NULL,
    C_PHONE       CHAR(15) NOT NULL,
    C_ACCTBAL     DECIMAL(15,2)   NOT NULL,
    C_MKTSEGMENT  CHAR(10) NOT NULL,
    C_COMMENT     VARCHAR(117) NOT NULL )
WITH (SQLSUFFIX)
DISTRIBUTED BY(C_CUSTKEY);

CREATE EXTERNAL WEB TABLE e_customer_TABLESUFFIX (
    C_CUSTKEY     INTEGER,
    C_NAME        VARCHAR(25),
    C_ADDRESS     VARCHAR(40),
    C_NATIONKEY   INTEGER,
    C_PHONE       CHAR(15),
    C_ACCTBAL     DECIMAL(15,2),
    C_MKTSEGMENT  CHAR(10),
    C_COMMENT     VARCHAR(117) ) 
EXECUTE E'bash -c "$GPHOME/bin/dbgen -b $GPHOME/bin/dists.dss -T c -s SCALEFACTOR -N NUMSEGMENTS -n $((GP_SEGMENT_ID + 1))"'
ON NUMSEGMENTS FORMAT 'TEXT' (DELIMITER '|');

INSERT INTO customer_TABLESUFFIX SELECT * FROM e_customer_TABLESUFFIX;
