-- ----------------------------------------------------------------------

DROP TABLE IF EXISTS lineitem_TABLESUFFIX CASCADE;
DROP EXTERNAL WEB TABLE IF EXISTS e_lineitem_TABLESUFFIX;

CREATE TABLE lineitem_TABLESUFFIX (
    L_ORDERKEY    INT8 NOT NULL,
    L_PARTKEY     INTEGER NOT NULL,
    L_SUPPKEY     INTEGER NOT NULL,
    L_LINENUMBER  INTEGER NOT NULL,
    L_QUANTITY    DECIMAL(15,2) NOT NULL,
    L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
    L_DISCOUNT    DECIMAL(15,2) NOT NULL,
    L_TAX         DECIMAL(15,2) NOT NULL,
    L_RETURNFLAG  CHAR(1) NOT NULL,
    L_LINESTATUS  CHAR(1) NOT NULL,
    L_SHIPDATE    DATE NOT NULL,
    L_COMMITDATE  DATE NOT NULL,
    L_RECEIPTDATE DATE NOT NULL,
    L_SHIPINSTRUCT CHAR(25) NOT NULL,
    L_SHIPMODE     CHAR(10) NOT NULL,
    L_COMMENT      VARCHAR(44) NOT NULL )
WITH (SQLSUFFIX)
DISTRIBUTED BY(L_ORDERKEY) PARTITIONS;

CREATE EXTERNAL WEB TABLE e_lineitem_TABLESUFFIX(
    L_ORDERKEY    INT8,
    L_PARTKEY     INTEGER,
    L_SUPPKEY     INTEGER,
    L_LINENUMBER  INTEGER,
    L_QUANTITY    DECIMAL(15,2),
    L_EXTENDEDPRICE  DECIMAL(15,2),
    L_DISCOUNT    DECIMAL(15,2),
    L_TAX         DECIMAL(15,2),
    L_RETURNFLAG  CHAR(1),
    L_LINESTATUS  CHAR(1),
    L_SHIPDATE    DATE,
    L_COMMITDATE  DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT CHAR(25),
    L_SHIPMODE     CHAR(10),
    L_COMMENT      VARCHAR(44) )
EXECUTE E'bash -c "$GPHOME/bin/dbgen -b $GPHOME/bin/dists.dss -T L -s SCALEFACTOR -N NUMSEGMENTS -n $((GP_SEGMENT_ID + 1))"' 
ON NUMSEGMENTS FORMAT 'TEXT' (DELIMITER '|')
LOG ERRORS INTO errortable_lineitem_TABLESUFFIX SEGMENT REJECT LIMIT 100 PERCENT;

INSERT INTO lineitem_TABLESUFFIX SELECT * FROM e_lineitem_TABLESUFFIX;

-- ----------------------------------------------------------------------

DROP EXTERNAL TABLE IF EXISTS lineitem_w_hdfstextsimple;
DROP EXTERNAL TABLE IF EXISTS lineitem_r_PXF_TABLE_SUFFIX;

CREATE WRITABLE EXTERNAL TABLE lineitem_w_hdfstextsimple (
    L_ORDERKEY    INT8,
    L_PARTKEY     INTEGER,
    L_SUPPKEY     INTEGER,
    L_LINENUMBER  INTEGER,
    L_QUANTITY    DECIMAL(15,2),
    L_EXTENDEDPRICE  DECIMAL(15,2),
    L_DISCOUNT    DECIMAL(15,2),
    L_TAX         DECIMAL(15,2),
    L_RETURNFLAG  CHAR(1),
    L_LINESTATUS  CHAR(1),
    L_SHIPDATE    DATE,
    L_COMMITDATE  DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT CHAR(25),
    L_SHIPMODE     CHAR(10),
    L_COMMENT      VARCHAR(44) )
    LOCATION ('pxf://PXF_NAMENODE:51200PXF_WRITABLE_PATH/lineitem_hdfstextsimple?PROFILE=HdfsTextSimple')
    FORMAT 'TEXT' (delimiter=E',');

INSERT INTO lineitem_w_hdfstextsimple SELECT * FROM lineitem_TABLESUFFIX;

CREATE READABLE EXTERNAL TABLE lineitem_r_PXF_TABLE_SUFFIX (
    L_ORDERKEY    INT8,
    L_PARTKEY     INTEGER,
    L_SUPPKEY     INTEGER,
    L_LINENUMBER  INTEGER,
    L_QUANTITY    DECIMAL(15,2),
    L_EXTENDEDPRICE  DECIMAL(15,2),
    L_DISCOUNT    DECIMAL(15,2),
    L_TAX         DECIMAL(15,2),
    L_RETURNFLAG  CHAR(1),
    L_LINESTATUS  CHAR(1),
    L_SHIPDATE    DATE,
    L_COMMITDATE  DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT CHAR(25),
    L_SHIPMODE     CHAR(10),
    L_COMMENT      VARCHAR(44) )
    LOCATION ('pxf://PXF_NAMENODE:51200/PXF_OBJECT_PATHlineitem_EXTERNAL_DATA_FORMAT?PROFILE=PXF_PROFILE')
    FORMAT 'PXF_FORMAT_TYPE' (PXF_FORMAT_OPTIONS);

-- ----------------------------------------------------------------------

